Numpy Tutorial

Arry

an arry is a collection of items stored at cotiguous memory location each identified by at least one array index or key. the idea is to store multiple items of the same type together

Numpy Tutorial

NumPy is a python package. it stands for 'Numerical python'. It is a library consisting of multidimenstional array object and a collection of routines for processing of array 

# NUMPY

In [1]:
import numpy

In [2]:
numpy.array([1,2,3,4,5]) 

array([1, 2, 3, 4, 5])

In [3]:
a=numpy.array([10,20,30,40,50,60])

In [4]:
a

array([10, 20, 30, 40, 50, 60])

In [12]:
# Size----> number of elements
a.size

6

atrribute no need to use parenthesis and also functions  needs parenthesis

In [5]:
b=numpy.array([34,44,54,64,78,89])

In [6]:
b

array([34, 44, 54, 64, 78, 89])

In [7]:
import numpy as np

In [8]:
a=np.array([45,23,78,56,12,666])

In [9]:
a

array([ 45,  23,  78,  56,  12, 666])

In [15]:
a.min()

12

In [10]:
b=np.array([100,203,304,405,608])

In [11]:
b

array([100, 203, 304, 405, 608])

In [13]:
b.size

5

In [16]:
b.min()

100

Class numpy 1.Atrribute - size no need to write -()

            2.function -min/max - use ()

reading purposes entere in help(numpy.min)

In [19]:
b.max()

608

In [21]:
b.shape

(5,)

(5,0) is the row is prsent no columns -it is one dimenstional rows without columns

In [22]:
# number of dimension
b.ndim

1

In [24]:
#type of data
b.dtype

dtype('int32')

In [25]:
b=np.array([45,78,23,89,22,11,10,98,56],dtype='int32')

In [26]:
b

array([45, 78, 23, 89, 22, 11, 10, 98, 56])

In [27]:
# shows memory bytes allocation to each element

b.itemsize

4

intem size means how many bytes allocation

In [28]:
# number of elements
b.size

9

int-4 byte

0101 1001 = 8bit=1 byte

32bit/8 =4 byte 

our integer data individual data stored with 4 byte



In [29]:
b.min()

10

In [30]:
b.max()

98

In [31]:
b.shape

(9,)

my dates are    c1   c2  
             r1 1     2
             r2 3     4

c=np.array([[C1,C2],[C1,C2]])

In [32]:
c=np.array([[1,2],[3,4]])

In [33]:
c

array([[1, 2],
       [3, 4]])

In [35]:
c.shape

(2, 2)

the shape is showing 2 rows & 2 columns

In [36]:
c.size

4

In [37]:
c.itemsize

4

In [38]:
c.ndim # number od dimension

2

here it is 2 dimension x & Y dim

In [40]:
c.min()

1

In [41]:
c.max()

4

In [42]:
c.dtype

dtype('int32')

In [44]:
c=np.array([[1,2],[3,4]],dtype='int64')

In [45]:
c

array([[1, 2],
       [3, 4]], dtype=int64)

In [46]:
c.itemsize

8

if you are entering difault 64 bites the item size will be 8 bytes

(3,2)....> 3 rows & 2 columns

In [47]:
d=np.array([[11,12],[13,14],[14,16]])

In [48]:
d

array([[11, 12],
       [13, 14],
       [14, 16]])

In [49]:
d.shape

(3, 2)

In [63]:
d.reshape(2,3)

array([[11, 12, 13],
       [14, 14, 16]])

In [50]:
d.ndim

2

With data (3,3) ....3 rows & 3 Coumns

In [51]:
x=np.array([[10,20,30],[40,50,60],[70,80,90]])

In [52]:
x

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [53]:
x.shape

(3, 3)

In [54]:
x.ndim

2

(4,3)....> 4 rows & 3 columns

In [55]:
y=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [56]:
y

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [57]:
y.shape

(4, 3)

In [58]:
y.ndim

2

In [59]:
y.itemsize

4

In [60]:
y.dtype

dtype('int32')

In [61]:
y.size

12

In [67]:
y.max()

12

In [68]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [69]:
np.arange(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [70]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
x=np.arange(15)

In [72]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [73]:
x.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [80]:
b=x.reshape(5,3)

In [81]:
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [82]:
b.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [75]:
p=np.arange(35)

In [76]:
p

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34])

In [78]:
p.reshape(7,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [79]:
p.reshape(5,7)

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [85]:
f=np.array([[11,12.2],[13,14],[14,16]],dtype='int32')

In [84]:
f

array([[11. , 12.2],
       [13. , 14. ],
       [14. , 16. ]])

np.arange(start,end)

In [86]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [88]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [89]:
np.arange(5,15)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [90]:
np.arange(10,25)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

Jumping in numbers

In [91]:
np.arange(0,10,1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [93]:
np.arange(0,25,5)

array([ 0,  5, 10, 15, 20])

In [94]:
np.arange(0,100,10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [95]:
b=np.arange(12).reshape(4,3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

Broadcasting in Numpy

The term Broadcasting describes how numpy treats array with different shapes during arithmitc operations. subject to certain constraints, the smaller array is "broadcast" across the larger array so that they have compatible shapes.Broadcasting provides a means of vectorizing array operations 

In [96]:
a=np.array([4,5,6])

In [97]:
b=np.array([3,3,4])

In [98]:
# Factorizing/multi
a*b

array([12, 15, 24])

In [99]:
c=2

In [100]:
a*c

array([ 8, 10, 12])

In [101]:
a+b

array([ 7,  8, 10])

In [102]:
b

array([3, 3, 4])

In [103]:
# b^2

b**2

array([ 9,  9, 16], dtype=int32)

In [106]:
b=np.random.random([2,3])

In [107]:
b

array([[0.36685385, 0.34242673, 0.39797247],
       [0.86917854, 0.70885256, 0.82494231]])

In [108]:
c=np.ones([2,3])

In [109]:
c

array([[1., 1., 1.],
       [1., 1., 1.]])

In [110]:
d=b+c
d

array([[1.36685385, 1.34242673, 1.39797247],
       [1.86917854, 1.70885256, 1.82494231]])

Universal function

In [111]:
B=np.arange(3)

In [112]:
B

array([0, 1, 2])

In [113]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [114]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [115]:
c=np.array([2,1,4])
np.add(B,c)

array([2, 2, 6])

Indexing, Slicing and Iterating

In [116]:
a=np.arange(10)

In [117]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [118]:
a[2]

2

In [119]:
# 2:5 start 2 end before 5
a[2:5]

array([2, 3, 4])

In [120]:
# last data shows
a[-1]

9

In [121]:
a[-2]

8

In [122]:
a[-3]

7

In [123]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [125]:
a[-4:]

array([6, 7, 8, 9])

In [126]:
a[-4:-2]

array([6, 7])

In [127]:
d2=np.arange(20)

In [129]:
d2[5:] #slicing from 5th index till end of the array

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [130]:
d3=np.array([np.nan,1,2,3,np.nan,6,7,8])
d3

array([nan,  1.,  2.,  3., nan,  6.,  7.,  8.])

nan is the reprocentation of missing data in numpy

the random module provides nice function to generate randam numbers (and also statistical distribution) of any given shape.rand function will generate any numbers between 0 and 1

In [131]:
np.random.rand(2,2)  # uniform distribution ...> similar like random

array([[0.01018201, 0.95893706],
       [0.04244931, 0.6768441 ]])

Randn will generate any number for normal distribution in the given dimenstion format

In [132]:
np.random.randn(2,3)

array([[ 0.01140548,  0.35167396, -1.95679402],
       [-0.51702714, -0.64502444,  0.37775005]])